image: coffeemate/nodejs

stages:
    - build
    - test
    - deploy

build_app:
    stage: build
    script:
        - yarn install
    artifacts:
        expire_in: 1 week
        untracked: true

test_app:
    stage: test
    script:
        - echo "Not implemented yet"

deploy_staging:
    stage: deploy
    script:
        - echo "Not implemented yet"
    except:
        - master

deploy_production:
    stage: deploy
    script:
        - echo "Not implemented yet"
    only:
        - master
